apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    app: python-app
spec:
  containers:
  - name: python-container
    image: seun0706/f-app1.1:latest #enter your application dockerhub image here
  - containerPort: 8000