apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: python-app
  labels:
    app: python-app
spec:
  containers:
  - image: seun0706/buildimage:latest
    name: python-app
    ports:
    - containerPort: 8000